stages:
  - generate
  - build
  - deploy

pricing:
  stage: generate
  script:
    - setsid ./price_calculator/push.sh
  only:
    refs:
      - /^main$/
    changes:
      - price_calculator/*
  tags:
    - cloud_doc

build:
  stage: build
  tags:
    - imagesbuilder
  rules: 
    - if: $CI_COMMIT_MESSAGE =~ /(Update pricing and push)/
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /main/ 
  script:
    - chmod +x ./ci/deliver.sh
    - ./ci/deliver.sh

deploy:
  stage: deploy
  needs:
    - build
  script:
    - chmod +x ./ci/deploy.sh
    - ./ci/deploy.sh
    - ./ci/notif.sh
  rules: 
    - if: $CI_COMMIT_MESSAGE =~ /(Update pricing and push)/
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /main/ 
  tags:
    - web
