version: '3.3'

services:
  comwork_cloud_doc:
    restart: always
    container_name: comwork_cloud_doc
    image: rg.fr-par.scw.cloud/cwcloud-ce-u7u1q0/cwcloud-doc:${VERSION}
    networks:
      - comwork_cloud_doc
    ports:
      - "5333:80"

networks:
  comwork_cloud_doc:
    driver: bridge
